# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Nbdevtut',
                'doc_host': 'https://Dhkj.github.io',
                'git_url': 'https://github.com/Dhkj/Nbdevtut',
                'lib_path': 'Nbdevtut'},
  'syms': {'Nbdevtut.core': {'Nbdevtut.core.foo': ('core.html#foo', 'Nbdevtut/core.py')}}}
